generator_args:
  jsonschema:
    include_range_class_descendants: true
  pydantic:

includes:
  - jsonschema
  - python
  - pydantic
excludes:
  - graphql
  - owl
  - shex
  - shacl
  - sqlschema
  - protobuf
  - prefixmap
mergeimports: true